### ISSUE TITLE
Any interest in import or require statements?

### ISSUE THREAD

**Issue by eddiesholl** [smallhelm/estree-builder#1]
This is a cool little library, I'm trying it out for some js code generation. Has there been any interest in filling out module constructs like import or require?

**Comment by farskipper** [comment]
Cool. Since this library is focused on just building estree nodes I don't think we should have special support for things that are just built on top; like common.js style modules. But I'm not opposed to adding the es6 modules `import/export` since those are just estree nodes.

Here's how to do common.js right now.
```js
var e = require("estree-builder");
var astring = require("astring").generate;


var mkReq = function(id, path){
    return e("var", id, e("call", e("id", "require"), [e("string", path)]));
};

console.log(astring(mkReq("test", "./some-path")));


var mkExport = function(value){
    return e(";", e("=", e("id", "module.export"), value));
};

console.log(astring(mkExport(e("string", "value"))));
```

output:
```js
var test = require("./some-path");
module.export = "value";
```

Hope that helps

**Comment by eddiesholl** [comment]
Nice. There's another great tip buried in there, which has been really useful: `id` can work as a last resort 'raw' mode to sneak in unsupported syntax.

Do you think fat arrow support is worth a PR?

**Comment by farskipper** [comment]
Sure! You can add any es2015+ things. I just haven't added them since I didn't have a need. Just follow the [estree](https://github.com/estree/estree) spec, and keep it backwards compatible. Thanks

**Comment by eddiesholl** [comment]
Thanks for your advice, I'll close this now.
